apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: indy-network-explorer-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
